locale_default: English
locale_ru: Русский (Russian)

title: Save Custom Games

title_line1: SAVE
title_line2: CUSTOM GAMES

introduction: INTRODUCTION
introduction_text: Custom Games in Dota represent a continuation of the tradition that gave birth to Dota, but morale within the custom game community is at an all time low. In the wake of the [Frostivus](https://www.reddit.com/r/DotA2/comments/7jvwwp/how_valve_completely_destroyed_custom_games_with/) [Fiasco](https://www.reddit.com/r/DotA2/comments/7bc84s/valve_this_custom_game_contest_is_a_bad_joke/), many developers are feeling betrayed and ignored by Valve, feeling that developing custom games is a hopeless uphill battle against a company that doesn’t care. Custom Games have a bright future but only with the support of Valve. Help us get that message to them. <br><br><b>Note - There are currently bots [spamming](https://www.reddit.com/r/DotA2/comments/7pvm1p/custom_games_not_playable_because_of_bots/) links to this website in custom game lobbies. This website is not associated with the bots and the modding community does not endorse the behaviour of these botters</b>.

complains:
  - title: IMPROVE COMMUNICATION
    video: /images/reason_communication
    text: Communication is what is needed most. Its understandable that Valve is not always interested in custom games and they have many different creative endeavours, but it's not unreasonable for 1 or 2 employees to touch base with the modding community on a regular basis. The [modding community](https://discord.gg/Mvn4gww) has tried to meet Valve halfway, creating and maintaining an extensive [bug-tracker](https://github.com/ModDota/BugTracker/issues), in hope that Valve will use this resource to address issues. Valve has viewed the tracker on a few occasions, mainly when Reddit threads containing the tracker made the front page. Valve is capable of this type of sustained cooperation as they have done a fantastic job building the bot API with the help of the community.
  - title: FIX FREQUENT PLAYER DISCONNECTS
    video: /images/reason_disconnects
    text: For [years](https://www.reddit.com/r/DotA2/comments/7ehmdt/how_can_it_still_be_after_literally_years_that/), custom games have been plagued with predictable and widespread disconnecting in the beginning phase of games. This problem affects most games, including Valve custom games, Overthrow and 10v10. This problem is usually fixed by reconnecting after a disconnect. The problem is entirely on Valve’s end, and unfortunately we cannot do anything about it from the standpoint as a custom game developer.
  - title: REVAMP ARCADE LAYOUT
    video: /images/reason_overview
    text: Replace the top 10 view list with a list of all lobbies, grouping lobbies and ranking lobbies by the amount of lobbies, remove workshop vote and fix the [problem](https://www.reddit.com/r/DotA2/comments/7lpdq7/suggestions_to_improve_open_lobbies_widget/) where players end up in solo lobbies when clicking play. A ping should be shown next to grouped lobbies to indicate the ping of the best lobby for the player in that group. Pressing the Play button on grouped lobbies should join the best lobby for the player. A “Local Lobbies” window should show custom games that only have one lobby and are in the same region as a player, this will allow newer custom games to be able to find players. Local lobbies should be ranked by age of lobby.
  - title: IMPROVE DEBUGGING TOOLS
    video: /images/reason_debugging
    text: Developers have little to no ability to track down information leading to the cause of various bugs and crashes, both in the local testing client and especially in the live servers. The types of crashes are wide in range, from some being as simple as a function being renamed by Valve, to others as complicated as an order crashing the server because the order ended up being invalid with the given parameters. This often leads to months of wasted time for developers to track down these bugs. Simple tools, such as the option to forward the server Lua output to a separate site or workshop page, enabling the specate button or re-enabling replays of custom games would help greatly.
  - title: AUTOMATED DEDICATED SERVERS
    video: /images/reason_servers
    text: Valve's [sporadic](https://www.reddit.com/r/DotA2/comments/6n18qx/something_must_change_about_custom_games_and/) and seemingly manual process of giving out dedicated servers to custom games has resulted in even popular games not having them, while older games that nobody plays anymore have dedicated servers. Developers have even resorted to cannibalizing older custom games entries to take advantage of their dedicated servers status (Open Angel Arena taking Pimp My Peon's Entry). Valve should instead automate the process of giving dedicated servers, so that once a game reaches a certain popularity, servers will be allocated, or reallocated if the game becomes unplayed.
  - title: PROVIDE CHANGELOG FOR API UPDATES
    video: /images/reason_updates
    text: For a company that prides itself on [supporting](https://imgur.com/jszUNxr) user generated content, it's strange that so little consideration is given for the modding community. Updating a dynamic game like DotA 2 is bound to [break](https://www.reddit.com/r/DotA2/comments/5iy4k5/700_is_killing_my_custom_game_and_i_cant_do/) custom games sometimes, but too frequently Valve makes slight or seemingly unnecessary changes (like renaming a function and then changing it back a month later) which breaks many custom games, leaving the community to scramble and try to figure out what has changed and what broke. It would be trivially easy for Valve to provide a simple changelog of updates to the API when they release updates and it would help modders recover much faster from game breaking updates.

what_you_can_do: WHAT YOU CAN DO
what_you_can_do_text: Tell Valve that custom games are important for Dota 2 community!

contacts:
  - text: Write to Dota 2 Custom Games team
    href: mailto:dotacustomgames@valvesoftware.com
    image: /images/contact_custom_team.png
  - text: Write to Dota 2 Team
    href: http://www.valvesoftware.com/email.php?recipient=Dota%202%20Team
    image: /images/contact_dota_team.png
  - text: Make a thread on Dota 2 Dev Forum
    href: https://dev.dota2.com/forumdisplay.php?f=484
    image: /images/contact_forum.png


developers_title: This was created and endorsed by the custom game community
developers:
  - name: FireToad
    icon: nyx
    flag: br
    made: |-
      * Creator of [Dota IMBA](https://steamcommunity.com/sharedfiles/filedetails/?id=440115357) and [Epic Boss Challenge](https://steamcommunity.com/sharedfiles/filedetails/?id=1138461301).
  - name: Ark120202
    icon: demon_edge
    flag: ru
    made: |-
      * Creator of [Angel Arena Black Star](https://steamcommunity.com/sharedfiles/filedetails/?id=699441891).
  - name: Avalon Studio
    icon: crest
    flag: cn
    made: |-
      * Creators of [Winterstorm](https://steamcommunity.com/sharedfiles/filedetails/?id=1205371753), [Realm Of Chaos - The Legend of Mt. Shu](https://steamcommunity.com/sharedfiles/filedetails/?id=866471631), [Touhou Defence of the Shrines](https://steamcommunity.com/sharedfiles/filedetails/?id=616333146), [NavalWarfare](https://steamcommunity.com/sharedfiles/filedetails/?id=524239685), [Realm of Chaos](https://steamcommunity.com/sharedfiles/filedetails/?id=520323982) and [Battle of Mirkwood](https://steamcommunity.com/sharedfiles/filedetails/?id=518202526).
  - name: Disorance
    icon: druid
    flag: ru
    made: |-
      * Creator of [Angel Arena Reborn](https://steamcommunity.com/sharedfiles/filedetails/?id=500020226).
  - name: Yahnich
    icon: alchemist
    flag: be
    made: |-
      * Lead Developer of [Epic Boss Fight](https://steamcommunity.com/sharedfiles/filedetails/?id=305278898) and developer for [The Second Day of Frostivus](http://steamcommunity.com/sharedfiles/filedetails/?id=1197063942).
  - name: ChalkyBrush
    icon: leshrac
    flag: ca
    made: |-
      * Creator of [Roshpit Champions](https://steamcommunity.com/sharedfiles/filedetails/?id=469311655).
  - name: SinZ
    icon: tome_of_knowledge
    flag: au
    made: |-
      * Acting Manager of [ModDota.com](https://moddota.com/).
  - name: StrangeR
    icon: naturesprophet
    flag: ru
    made: |-
      * Creator of [BIRZHA MEMOV](https://steamcommunity.com/sharedfiles/filedetails/?id=932631669).
  - name: Zapp Brannigan
    icon: bristleback
    flag: va
    made: |-
      * Lead Developer of [WTF+](https://steamcommunity.com/sharedfiles/filedetails/?id=476601122).
  - name: Cookies
    icon: earthspirit
    flag: fr
    made: |-
      * Lead Developer of [Dota IMBA](https://steamcommunity.com/sharedfiles/filedetails/?id=440115357), creator of [X Hero Siege](https://steamcommunity.com/sharedfiles/filedetails/?id=536682348), [All Bosses Challenge](https://steamcommunity.com/sharedfiles/filedetails/?id=520277859) and [Epic Boss Challenge](https://steamcommunity.com/sharedfiles/filedetails/?id=1138461301).
  - name: DoctorGester
    icon: tinker
    flag: ru
    made: |-
      * Creator of [Crumbling Island Arena](http://steamcommunity.com/sharedfiles/filedetails/?id=473718711) and [It's Greeviling!](http://steamcommunity.com/sharedfiles/filedetails/?id=1201422751).
  - name: XavierCHN
    icon: invoker
    flag: cn
    made: |-
      * Creator of [Battle of Mirkwood](https://steamcommunity.com/sharedfiles/filedetails/?id=518202526&searchtext=), [BOM BattleRoyale](https://steamcommunity.com/sharedfiles/filedetails/?id=1092484716), [NavalWarfare](https://steamcommunity.com/sharedfiles/filedetails/?id=524239685) and [Feastivus](https://steamcommunity.com/sharedfiles/filedetails/?id=1165493298).
  - name: Baumi
    icon: lotus_orb
    flag: de
    made: |-
      * [Youtube Personality](https://www.youtube.com/channel/UCmxX0QwCivAbRAXvPbEid8Q) and [Twitch Streamer](https://www.twitch.tv/l34um1). Creator of [Open Angel Arena](http://steamcommunity.com/sharedfiles/filedetails/?id=513926896), [The Second Day of Frostivus](http://steamcommunity.com/sharedfiles/filedetails/?id=1197063942) and sponsor of [Pimp My Peon](https://steamcommunity.com/sharedfiles/filedetails/?id=972949462).
  - name: Diellan
    icon: rubick
    flag: il
    made: |-
      * Creator of [Dota 2 Horde Mode](https://steamcommunity.com/sharedfiles/filedetails/?id=472597026).
  - name: Shooper
    icon: mek
    flag: us
    made: |-
      * Creator of [SWAT: Reborn](http://steamcommunity.com/sharedfiles/filedetails/?id=725282388) and [Snow Brawl](http://steamcommunity.com/sharedfiles/filedetails/?id=1200619594).
  - name: Arhowk
    icon: pudge
    flag: us
    made: |-
      * Creator of [Snowtown Throwdown](http://steamcommunity.com/sharedfiles/filedetails/?id=1158412580&searchtext=), ["Diablo 2 in Dota 2"](https://www.reddit.com/r/DotA2/comments/6uc841/diablo_2_in_dota_2_needs_your_help/) project and developer for [Banjoball Alpha](https://steamcommunity.com/sharedfiles/filedetails/?id=669883818).
  - name: TidesofDark
    icon: viper
    flag: ru
    made: |-
      * Creator of [Petri Reborn](https://steamcommunity.com/sharedfiles/filedetails/?id=483720948) and [Feastivus](https://steamcommunity.com/sharedfiles/filedetails/?id=1165493298) and developer for [Legends of Dota: Redux](https://steamcommunity.com/sharedfiles/filedetails/?id=717356279).
  - name: Toyoka
    icon: wisp
    flag: ca
    made: |-
      * Creator of [Snowtown Throwdown](http://steamcommunity.com/sharedfiles/filedetails/?id=1158412580&searchtext=) and [Wisp Cosmetic Set](http://steamcommunity.com/sharedfiles/filedetails/?id=1182695521).
  - name: Usagi Majo Arctangent
    icon: mindstealer
    flag: us
    made: |-
      * Creator of [Bob Wars](https://steamcommunity.com/sharedfiles/filedetails/?id=904834212&searchtext=), [DOTA 2 But ...](https://steamcommunity.com/sharedfiles/filedetails/?id=838016297), [Randymizer](https://steamcommunity.com/sharedfiles/filedetails/?id=964909547), [DOTA 2 but every Hero is secretly also Chen](https://steamcommunity.com/sharedfiles/filedetails/?id=830359459), [ARAM: Murder Isthmus](https://steamcommunity.com/sharedfiles/filedetails/?id=1170382864) and developer for [The Second Day of Frostivus](http://steamcommunity.com/sharedfiles/filedetails/?id=1197063942).
  - name: Chrisinajar
    icon: bottle
    flag: us
    made: |-
      * [Open source contributor](https://github.com/chrisinajar) and creator of [Open Angel Arena](http://steamcommunity.com/sharedfiles/filedetails/?id=513926896), [The Second Day of Frostivus](http://steamcommunity.com/sharedfiles/filedetails/?id=1197063942) and pre-reborn mod 'MNI Mode'.
  - name: Mocherad
    icon: dagon_3
    flag: ua
    made: |-
      * Creator of [Pure Reflex](https://steamcommunity.com/sharedfiles/filedetails/?id=575540979), [Frostivus: The Snowman's Story](https://steamcommunity.com/sharedfiles/filedetails/?id=1209178917), [Duel](https://steamcommunity.com/sharedfiles/filedetails/?id=867129063) and [Feastivus](https://steamcommunity.com/sharedfiles/filedetails/?id=1165493298).
  - name: Vendivar
    icon: troll
    flag: us
    made: |-
      * Creator of [Island Troll Tribes 2](https://steamcommunity.com/sharedfiles/filedetails/?id=801065815).
  - name: Bread
    icon: puck
    flag: au
    made: |-
      * Creator of [Dusk](https://steamcommunity.com/sharedfiles/filedetails/?id=426167013).
  - name: Darklord
    icon: shadowfiend
    flag: au
    made: |-
      * Lead Developer of [Legends of Dota: Redux](https://steamcommunity.com/sharedfiles/filedetails/?id=717356279) and creator of [Feastivus](https://steamcommunity.com/sharedfiles/filedetails/?id=1165493298).
